version: "3"
services:
  app:
    container_name: express-mongo
    restart: always
    # prevent exit
    # https://stackoverflow.com/questions/38546755/docker-compose-keep-container-running
    tty: true
    build: ./
    ports:
      - "80:3000"
    volumes:
      - .:/app
      - /app/node_modules
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo:3.4
    ports:
      - "27017:27017"
